const RouteName = {
  SPLSH: 'SplashScreen',
  SWIPER_SCREEN: 'Swiperscreen',
  LOGIN_SCREEN: 'LoginScreen',
  REGISTER_SCREEN: 'Register',
  OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
  HOME_SCREEN: 'HomeScreen',
  SIDE_NAVIGATOR: 'SideNavigator',
  REGIATRAION_SUCCESSFULL: 'RegistrationSuccessful',
  HOME_TAB: 'Homess',
  LEADERBOARD: 'Leaderboards',
  HISTORYTAB: 'HistoryTabs',
  WALLETS_TAB: 'Wallets',
  PROFILE_TAB: 'Profiles',
  SELECT_LANGUAGE: 'TranslationScreen',
  FORGOT_PASSWORD: 'ForgotPassword',
  CHAT_SCREEN: 'Chatscreen',
  HELP_SCREEN: 'HelpScreen',
  SETTING_SCREEN: 'SettingsScreen',
  FAQ_SCREEN: 'FAQScreen',
  REVIEWS_SCREEN: 'ReviewsScreen',
  NOTIFICTION_SCREEN: 'NotificationScreen',
  HOME_DETAILS_SCREEN: 'HomeDetailsScreen',
  HOUSE_SCREENS: 'HouseScreens',
  AUDIO_CALL_SCREEN: 'AudioCall',
  PRACTICE_MAIN: 'PracticeMain',
  QUESTIONS: 'Questions',
  EXAM_REVIEW: 'ExamReview',
  ANSWER: 'Answer',
  YOUR_FRIEND: 'YourFriend',
};
export default RouteName;
